name: stock_predictor_pro
description: A real-time stock market prediction app with portfolio, news, and billionaire insights.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  http: ^1.2.0
  provider: ^6.1.2
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  lottie: ^3.1.2
  web_socket_channel: ^2.3.0
  fl_chart: ^0.60.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/
